services:

  web:
    build:
      context: ../../
      dockerfile: infra/docker/web.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../apps/api/.env
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app/apps/web
      - /app/node_modules
      - /app/apps/web/node_modules
    networks:
      - gitmaster

  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../apps/api/.env
    environment:
      - DATABASE_URL=postgresql://gitmaster:gitmaster@db:5432/gitmaster
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ../../apps/api:/app/apps/api
      - /app/node_modules
      - /app/apps/api/node_modules
    networks:
      - gitmaster

  worker:
    build:
      context: ../../
      dockerfile: infra/docker/worker.Dockerfile
    env_file:
      - ../../apps/api/.env
    environment:
      - DATABASE_URL=postgresql://gitmaster:gitmaster@db:5432/gitmaster
      - REDIS_URL=redis://redis:6379
    depends_on:
      - api
      - redis
      - db
    volumes:
      - ../../apps/worker:/app/apps/worker
      - /app/node_modules
      - /app/apps/worker/node_modules
    networks:
      - gitmaster

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gitmaster
      POSTGRES_PASSWORD: gitmaster
      POSTGRES_DB: gitmaster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gitmaster

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - gitmaster

volumes:
  postgres_data:


networks:
  gitmaster:
